// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYppLXD0Cnp8-ABcXDhCG2EtgPgF8P3vA',
    appId: '1:936341539005:web:93903a9e82e57b807d8fd4',
    messagingSenderId: '936341539005',
    projectId: 'notes-316f5',
    authDomain: 'notes-316f5.firebaseapp.com',
    storageBucket: 'notes-316f5.appspot.com',
    measurementId: 'G-L0JTP2VCFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDynZrfWe0sq8Rws72Ka0vYTgAgRCVxGW0',
    appId: '1:936341539005:android:ecb5345999c19a557d8fd4',
    messagingSenderId: '936341539005',
    projectId: 'notes-316f5',
    storageBucket: 'notes-316f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDut5CEjs-wSVqqFZqQjMD32WHkbHzSxpc',
    appId: '1:936341539005:ios:8cf03256d24d411c7d8fd4',
    messagingSenderId: '936341539005',
    projectId: 'notes-316f5',
    storageBucket: 'notes-316f5.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDut5CEjs-wSVqqFZqQjMD32WHkbHzSxpc',
    appId: '1:936341539005:ios:8cf03256d24d411c7d8fd4',
    messagingSenderId: '936341539005',
    projectId: 'notes-316f5',
    storageBucket: 'notes-316f5.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYppLXD0Cnp8-ABcXDhCG2EtgPgF8P3vA',
    appId: '1:936341539005:web:cd81425a1ba65b667d8fd4',
    messagingSenderId: '936341539005',
    projectId: 'notes-316f5',
    authDomain: 'notes-316f5.firebaseapp.com',
    storageBucket: 'notes-316f5.appspot.com',
    measurementId: 'G-KHC08ZQY78',
  );
}
